INFO     src.api.package_route_api:package_route_api.py:13 API Client initialized with base URL: http://localhost:5000
INFO     src.api.package_route_api:package_route_api.py:21 Sending POST request to http://localhost:5000/packages/ingest with image: /tmp/pytest-of-runner/pytest-0/test_successful_ingestion0/test_package.jpg
ERROR    src.api.package_route_api:package_route_api.py:31 Error ingesting package from /tmp/pytest-of-runner/pytest-0/test_successful_ingestion0/test_package.jpg: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /packages/ingest (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff55b8c3670>: Failed to establish a new connection: [Errno 111] Connection refused'))