INFO:src.api.package_route_api:Sending POST request to http://localhost:5000/packages/ingest with image: /tmp/pytest-of-runner/pytest-0/test_ingest_invalid_image_form0/invalid_file.txt
ERROR:src.api.package_route_api:Error ingesting package from /tmp/pytest-of-runner/pytest-0/test_ingest_invalid_image_form0/invalid_file.txt: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /packages/ingest (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff55b68d4f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
